import {jobEvidence} from '../server/opportunity-recheck.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,readFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import http from 'node:http';
import {createAutomationConsole,ingestSignature} from '../server/automation-console.mjs';import {saveDraft} from '../server/instagram-queue.mjs';import {newYorkSchedule} from '../server/scheduling.mjs';
import {createMetaAuthorization} from '../server/meta-authorization.mjs';
test('New York scheduling handles daylight saving and rejects repeated or nonexistent clock times',()=>{
 assert.equal(newYorkSchedule('2026-10-07T09:00'),'2026-10-07T13:00:00.000Z');assert.equal(newYorkSchedule('2026-12-07T09:00'),'2026-12-07T14:00:00.000Z');assert.throws(()=>newYorkSchedule('2027-03-14T02:30'),/daylight/);assert.throws(()=>newYorkSchedule('2026-11-01T01:30'),/daylight/);assert.throws(()=>newYorkSchedule('2026-02-30T09:00'),/daylight|Invalid/);
});
test('private Meta connection checks administrator, state binding, expected account and encrypted storage; ingestion cannot schedule',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'cancha-meta-fixture-'));const password='fixture-password-'.repeat(4),appSecret='fixture-app-secret',ingestSecret='fixture-ingest-'.repeat(4),origin='https://cancha-fixture.example';let calls=0;const sourceUrl='https://www.teamworkonline.com/soccer-jobs/usl-soccer-jobs/miami-fc-jobs/fixture-job-123',sourceHtml='<script type="application/ld+json">'+JSON.stringify({'@type':'JobPosting',title:'Fixture job',validThrough:'2099-11-01'})+'</script><a href="/employment_opportunities/123/applications/new">Apply Now</a>';
 const fetchImpl=async(input,options)=>{calls++;const url=new URL(input);if(url.hostname==='www.teamworkonline.com')return new Response(sourceHtml,{headers:{'Content-Type':'text/html'}});if(url.pathname.endsWith('/oauth/access_token'))return Response.json({access_token:url.searchParams.has('fb_exchange_token')?'fixture-long-token':'fixture-short-token',expires_in:3600});assert.equal(options.headers.Authorization,'Bearer fixture-long-token');return Response.json({data:[{id:'123',name:'Cancha',access_token:'fixture-page-token',instagram_business_account:{id:'456',username:'wearecancha'}}]});};
 const statusToken='fixture-status-'.repeat(4);const admin=createAutomationConsole({baseUrl:origin,password,encryptionKey:'fixture-vault-key-'.repeat(3),vaultPath:join(dir,'meta.sqlite'),queuePath:join(dir,'queue.sqlite'),appId:'789',appSecret,version:'v99.0',accountType:'BUSINESS',ingestSecret,statusToken,fetchImpl});
 const server=http.createServer((req,res)=>admin.handle(req,res));await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;const request=(path,options={})=>fetch(url+path,{redirect:'manual',...options});
 try{
  saveDraft(admin.db,{id:'brand-fixture',format:'feed',caption:'Fixture private draft',altText:'Fixture image',assetUrl:'https://framerusercontent.com/images/fixture.jpg',sourceType:'brand'});
  let response=await request('/admin');assert.doesNotMatch(await response.text(),/Fixture private draft/);
  response=await request('/auth/meta/start',{method:'POST',headers:{Origin:origin}});assert.equal(response.status,401);
  response=await request('/admin/login',{method:'POST',headers:{Origin:'https://other.example'},body:new URLSearchParams({password})});assert.equal(response.status,403);
  response=await request('/admin/login',{method:'POST',headers:{Origin:origin},body:new URLSearchParams({password})});assert.equal(response.status,303);const session=response.headers.get('set-cookie').split(';')[0];assert.match(response.headers.get('set-cookie'),/HttpOnly/);
  response=await request('/auth/meta/start',{method:'POST',headers:{Origin:origin,Cookie:session}});assert.equal(response.status,303);const state=new URL(response.headers.get('location')).searchParams.get('state'),stateCookie=response.headers.get('set-cookie').split(';')[0];assert.equal(stateCookie.split('=')[1],state);
  response=await request('/auth/meta/callback?state='+state+'&code=fixture-code',{headers:{Cookie:session}});assert.equal(response.status,400);assert.equal(calls,0);
  response=await request('/auth/meta/callback?state='+state+'&code=fixture-code',{headers:{Cookie:session+'; '+stateCookie}});assert.equal(response.status,303);assert.equal(admin.vault.read().username,'wearecancha');assert.equal(calls,3);
  const bytes=await readFile(join(dir,'meta.sqlite'));assert.equal(bytes.includes(Buffer.from('fixture-page-token')),false);
  response=await request('/auth/meta/callback?state='+state+'&code=fixture-code',{headers:{Cookie:session+'; '+stateCookie}});assert.equal(response.status,400);assert.equal(calls,3);
  response=await request('/admin',{headers:{Cookie:session}});const html=await response.text();assert.match(html,/Fixture private draft/);assert.doesNotMatch(html,/fixture-page-token|fixture-long-token|fixture-app-secret/);
  response=await request('/automation/status',{headers:{Authorization:'Bearer undefined'}});assert.equal(response.status,401);response=await request('/automation/status',{headers:{Authorization:'Bearer '+statusToken}});assert.equal(response.status,200);const status=await response.text();assert.match(status,/wearecancha/);assert.doesNotMatch(status,/fixture-page-token|fixture-long-token|Fixture private draft/);
  const row={id:'opportunity-123',format:'feed',sourceType:'opportunity',factsCheckedAt:new Date().toISOString(),caption:'Source fixture',altText:'Fixture image',assetUrl:'https://framerusercontent.com/images/fixture.jpg',assetChecksum:'a'.repeat(64),status:'Approved',scheduledAt:new Date().toISOString()};const payload=Buffer.from(JSON.stringify([row])),timestamp=String(Date.now());
  response=await request('/automation/drafts',{method:'POST',headers:{'Content-Type':'application/json','x-cancha-timestamp':timestamp,'x-cancha-signature':'sha256='+'0'.repeat(64)},body:payload});assert.equal(response.status,401);
  const options={method:'POST',headers:{'Content-Type':'application/json','x-cancha-timestamp':timestamp,'x-cancha-signature':ingestSignature(ingestSecret,timestamp,payload)},body:payload};response=await request('/automation/drafts',options);assert.equal(response.status,201);assert.equal(admin.db.prepare('SELECT status FROM instagram_queue WHERE id=?').get('opportunity-123').status,'Draft');response=await request('/automation/drafts',options);assert.equal(response.status,200);
  response=await request('/admin/instagram/approve',{method:'POST',headers:{Cookie:session,Origin:origin},body:new URLSearchParams({id:'brand-fixture',scheduledAt:'2099-10-07T09:00'})});assert.equal(response.status,422);
  response=await request('/admin/instagram/approve',{method:'POST',headers:{Cookie:session,Origin:origin},body:new URLSearchParams({id:'brand-fixture',scheduledAt:'2099-10-07T09:00',reviewed:'yes'})});assert.equal(response.status,303);assert.equal(admin.db.prepare('SELECT status FROM instagram_queue WHERE id=?').get('brand-fixture').status,'Approved');
  response=await request('/admin/instagram/edit',{method:'POST',headers:{Cookie:session,Origin:origin},body:new URLSearchParams({id:'brand-fixture',caption:'Changed caption',altText:'Changed alt'})});assert.equal(response.status,409);
  response=await request('/admin/instagram/unschedule',{method:'POST',headers:{Cookie:session,Origin:origin},body:new URLSearchParams({id:'brand-fixture'})});assert.equal(response.status,303);assert.equal(admin.db.prepare('SELECT status FROM instagram_queue WHERE id=?').get('brand-fixture').status,'Draft');
  response=await request('/admin/instagram/edit',{method:'POST',headers:{Cookie:session,Origin:origin},body:new URLSearchParams({id:'brand-fixture',caption:'Changed caption',altText:'Changed alt'})});assert.equal(response.status,303);assert.equal(JSON.parse(admin.db.prepare('SELECT content FROM instagram_queue WHERE id=?').get('brand-fixture').content).caption,'Changed caption');
  saveDraft(admin.db,{...row,officialSourceUrl:sourceUrl,sourceHash:jobEvidence(sourceHtml,sourceUrl).hash});
  response=await request('/admin/instagram/approve',{method:'POST',headers:{Cookie:session,Origin:origin},body:new URLSearchParams({id:row.id,scheduledAt:'2099-10-07T09:00',reviewed:'yes'})});assert.equal(response.status,303);const sourceApproval=admin.db.prepare('SELECT status,source_rechecked_at FROM instagram_queue WHERE id=?').get(row.id);assert.equal(sourceApproval.status,'Approved');assert.ok(sourceApproval.source_rechecked_at);
  const snapshot={projectId:'GU8EIeQXaRbty0S23thu',collectionName:'Opportunities',capturedAt:new Date().toISOString(),fields:[],items:[{id:'fixture-private-backup'}]},snapshotBytes=Buffer.from(JSON.stringify(snapshot)),stamp=String(Date.now());
  response=await request('/automation/opportunity-backup',{method:'POST',headers:{'Content-Type':'application/json','x-cancha-timestamp':stamp,'x-cancha-signature':ingestSignature(ingestSecret,stamp,snapshotBytes)},body:snapshotBytes});assert.equal(response.status,201);const receipt=await response.json();assert.deepEqual(admin.vault.readBackup(receipt.hash),snapshot);assert.equal((await readFile(join(dir,'meta.sqlite'))).includes(Buffer.from('fixture-private-backup')),false);
  response=await request('/admin/meta/disconnect',{method:'POST',headers:{Cookie:session,Origin:origin}});assert.equal(response.status,303);assert.equal(admin.vault.read(),null);
 }finally{await new Promise(r=>server.close(r));admin.close();await rm(dir,{recursive:true,force:true});}
});
test('Meta authorization refuses a different Instagram account and does not expose tokens in errors',async()=>{
 const authorization=createMetaAuthorization({appId:'123',appSecret:'fixture-app-secret',version:'v99.0',baseUrl:'https://fixture.example',fetchImpl:async input=>new URL(input).pathname.endsWith('/me/permissions')?Response.json({data:['pages_show_list','pages_read_engagement','instagram_basic','instagram_content_publish'].map(permission=>({permission,status:'granted'}))}):new URL(input).pathname.includes('oauth/access_token')?Response.json({access_token:'fixture-token'}):Response.json({data:[{id:'1',access_token:'fixture-wrong-page-token',instagram_business_account:{id:'2',username:'wrong-account'}}]})});await assert.rejects(authorization.exchange('fixture-code'),error=>error.message.includes('expected Instagram account')&&!error.message.includes('fixture-wrong-page-token'));
});
