import test from 'node:test';import assert from 'node:assert/strict';import {stageBatch} from '../server/opportunity-staging.mjs';
function setup(){const names={Title:'string',Organization:'string',Category:'enum',Sport:'enum',City:'string',Region:'enum',State:'string',Level:'enum','Age Group':'enum',Gender:'enum',Cost:'string','Short Description':'string','External Registration Link':'link',Image:'image','Image Treatment':'string','Full Description':'formattedText','Start Date':'date','End Date':'date',Status:'enum',Verified:'boolean',Featured:'boolean','Review Status':'string','Review Note':'string','Review Checked On':'date','Image Background':'string','Image Max Width':'number','Automation ID':'string','Automation Added On':'date','Automation Source Hash':'string'};
 const fields=Object.entries(names).map(([name,type])=>({id:name,name,type,...(type==='enum'?{cases:['Active','Pending review','Job','Soccer','South Florida','Professional','See eligibility','All'].map(name=>({id:name,name}))}:{})}));let items=[{id:'original',slug:'preserved-url',fieldData:{Title:{value:'Original listing'},Organization:{value:'Original organizer'},'External Registration Link':{value:'https://fixture.example/original'}}}],writes=0;
 const c={name:'Opportunities',getFields:async()=>fields,getItems:async()=>structuredClone(items),addItems:async rows=>{writes++;items.push(...rows.map((x,i)=>({...x,id:'new-'+i})));}};return {f:{getCollections:async()=>[c]},get writes(){return writes;},get items(){return items;}};
}
function row(){const now=new Date().toISOString();return {slug:'fixture-new-job',title:'Fixture new role',organization:'Fixture FC',category:'Job',sport:'Soccer',city:'Miami',region:'South Florida',state:'Florida',level:'Professional',ageGroup:'See eligibility',gender:'All',cost:'See employer',shortDescription:'Fixture only',fullDescription:'Fixture role qualifications',registrationUrl:'https://fixture.example/new-job',officialSourceUrl:'https://fixture.example/new-job',eligibilityEvidence:'Fixture evidence',availabilityEvidence:'Fixture evidence',dateEvidence:'No deadline inferred',imageUrl:'https://framerusercontent.com/images/fixture.png',imageRightsEvidence:'Fixture only',imageContext:'Fixture branding',imageTreatment:'Badge',imageWidth:500,imageHeight:500,openConfirmed:true,imageApproved:true,reviewer:'Fixture automated system',reviewedAt:now,sourceCheckedAt:now,reviewMode:'automated-source-check',automationChecks:Array(8).fill('fixture-check'),sourceHash:'a'.repeat(64)};}
const config={maximumPerRun:5,maximumSourceAgeHours:72};
test('publish-ready supported records preserve originals and stay unpublished; failed private backup prevents CMS mutation',async()=>{
 let state=setup();const original=structuredClone(state.items[0]);const result=await stageBatch(state.f,[row()],config,{apply:true,readyForPublish:true,beforeWrite:async snapshot=>{assert.equal(state.writes,0);assert.equal(snapshot.items.length,1);assert.equal(snapshot.projectId,'GU8EIeQXaRbty0S23thu');}});assert.equal(result.published,false);assert.deepEqual(state.items[0],original);assert.equal(state.items[1].draft,false);assert.equal(state.items[1].fieldData.Status.value,'Active');assert.equal(state.items[1].fieldData.Verified.value,false);
 state=setup();await assert.rejects(stageBatch(state.f,[row()],config,{apply:true,readyForPublish:true,beforeWrite:async()=>{throw Error('Private backup unavailable');}}),/backup unavailable/);assert.equal(state.writes,0);
 state=setup();await stageBatch(state.f,[row()],config,{apply:true});assert.equal(state.items[1].draft,true);assert.equal(state.items[1].fieldData.Status.value,'Pending review');
 state=setup();await assert.rejects(stageBatch(state.f,[{...row(),reviewMode:'human'}],config,{apply:true,readyForPublish:true}),/strict/);assert.equal(state.writes,0);
});
