import {confirmOpportunitySource} from './opportunity-recheck.mjs';
import {createHmac,createHash,timingSafeEqual} from 'node:crypto';import {openMetaVault} from './meta-vault.mjs';import {createMetaAuthorization,MetaConnectionError} from './meta-authorization.mjs';import {openQueue,saveDraft,approve} from './instagram-queue.mjs';import {newYorkSchedule} from './scheduling.mjs';
const esc=x=>String(x??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const digest=x=>createHash('sha256').update(x).digest();const equal=(a,b)=>timingSafeEqual(digest(a),digest(b));
export function ingestSignature(secret,timestamp,bytes){return 'sha256='+createHmac('sha256',secret).update(timestamp+'\n').update(bytes).digest('hex');}
async function body(req,max=65536){let size=0;const chunks=[];for await(const chunk of req){size+=chunk.length;if(size>max)throw Error('Request too large');chunks.push(chunk);}return Buffer.concat(chunks);}
function cookie(req,name){const raw=String(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(name+'='));return raw?.slice(name.length+1)||'';}
export function createAutomationConsole({baseUrl,password,encryptionKey,vaultPath,queuePath,appId,appSecret,version,loginConfigId,expectedPageId,accountType,ingestSecret,statusToken,reviewer='Cancha account owner',fetchImpl=fetch}){
 const base=new URL(baseUrl),origin=base.origin;if(base.protocol!=='https:'||base.username||base.password||base.pathname!=='/'||typeof password!=='string'||password.length<32)throw Error('Configure HTTPS service URL and secure administrator password');
 const vault=openMetaVault(vaultPath,encryptionKey),db=openQueue(queuePath);db.exec('CREATE TABLE IF NOT EXISTS ingest_receipts(hash TEXT PRIMARY KEY,created_at TEXT NOT NULL)');
 const authorization=appId&&appSecret&&version?createMetaAuthorization({appId,appSecret,version,baseUrl:origin,loginConfigId,expectedPageId,accountType,fetchImpl}):null;
 const sessionsSecret=createHmac('sha256',password).update('cancha-admin-sessions').digest();
 function session(){const value=Buffer.from(JSON.stringify({expires:Date.now()+60*60000})).toString('base64url');return value+'.'+createHmac('sha256',sessionsSecret).update(value).digest('hex');}
 function authenticated(req){const value=cookie(req,'cancha_admin'),parts=value.split('.');if(parts.length!==2||!equal(parts[1],createHmac('sha256',sessionsSecret).update(parts[0]).digest('hex')))return false;try{return JSON.parse(Buffer.from(parts[0],'base64url')).expires>Date.now();}catch{return false;}}
 const attempts=new Map();
 function send(res,status,text,headers={}){res.writeHead(status,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin','Content-Security-Policy':"default-src 'none'; style-src 'unsafe-inline'; img-src https://framerusercontent.com; form-action 'self' https://www.facebook.com; frame-ancestors 'none'; base-uri 'none'",...headers});res.end(text);}
 function redirect(res,path,headers={}){send(res,303,'',{'Location':path,...headers});}
 const shell=content=>`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cancha content review</title><style>body{font:17px/1.5 system-ui,sans-serif;margin:0;background:#f4f2ec;color:#0c3e2e}main{max-width:950px;padding:32px 20px;margin:auto}h1,h2{line-height:1.15}article{background:white;border-radius:16px;padding:24px;margin:24px 0}img{max-width:320px;width:100%;height:auto;display:block}pre{white-space:pre-wrap;font:inherit}input,button{font:inherit;padding:12px;margin:8px 4px 8px 0;max-width:100%;box-sizing:border-box}button{background:#0c3e2e;color:white;border:0;border-radius:8px;cursor:pointer}a{color:#0c3e2e}label{display:block}.notice{background:#ffe7dc;padding:16px;border-radius:12px}</style></head><body><main>${content}</main></body></html>`;
 function render(){const connection=vault.read(),rows=db.prepare('SELECT * FROM instagram_queue ORDER BY scheduled_at,id').all();return shell(`<h1>Cancha content review</h1><p>Review each design and caption before scheduling. Schedule times use New York time.</p><p>${connection?'Connected: @'+esc(connection.username):'Instagram is not connected.'}</p>${authorization?'<form action="/auth/meta/start" method="post"><button>Connect / reconnect Instagram</button></form>':'<p class="notice">Configure the real Meta app ID, app secret and supported Graph API version in hosting settings to enable connection.</p>'}${connection?'<form action="/admin/meta/disconnect" method="post"><button>Disconnect Instagram and cancel pending schedules</button></form>':''}<p>Posts scheduled here appear in this private queue. Custom API schedules do not automatically appear in Meta Business Suite Planner.</p>${rows.map(stored=>{const row=JSON.parse(stored.content);return `<article><h2>${esc(row.headline||row.id)}</h2><p><strong>${esc(stored.status)}</strong>${stored.scheduled_at?' — '+esc(new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',dateStyle:'medium',timeStyle:'short'}).format(new Date(stored.scheduled_at)))+' New York':''}</p>${row.assetUrl?'<img src="'+esc(row.assetUrl)+'" alt="'+esc(row.altText)+'">':''}<pre>${esc(row.caption)}</pre><p>${esc(stored.note)}</p>${stored.source_rechecked_at?'<p>Last automatic source check: '+esc(new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',dateStyle:'medium',timeStyle:'short'}).format(new Date(stored.source_rechecked_at)))+' New York</p>':''}${stored.status==='Draft'?`<details><summary>Edit caption and image description</summary><form action="/admin/instagram/edit" method="post"><input name="id" type="hidden" value="${esc(row.id)}"><label>Caption<textarea name="caption" rows="8" maxlength="2200" style="width:100%" required>${esc(row.caption)}</textarea></label><label>Image description<textarea name="altText" rows="3" maxlength="1000" style="width:100%" required>${esc(row.altText)}</textarea></label><button>Save edits for review</button></form></details>`:''}${['Approved','Preparing'].includes(stored.status)?`<form action="/admin/instagram/unschedule" method="post"><input name="id" type="hidden" value="${esc(row.id)}"><button>Cancel schedule and review again</button></form>`:''}${stored.status==='Draft'&&connection?`<form action="/admin/instagram/approve" method="post"><input name="id" type="hidden" value="${esc(row.id)}"><label>Publish time (New York)<input name="scheduledAt" type="datetime-local" step="60" required></label><label><input type="checkbox" name="reviewed" value="yes" required>I reviewed the image, caption, links and current source facts.</label><button>Approve and schedule</button></form>`:''}</article>`;}).join('')}<form action="/admin/logout" method="post"><button>Sign out</button></form>`);}
 return {handles(path){return ['/admin','/admin/login','/admin/logout','/auth/meta/start','/auth/meta/callback','/admin/meta/disconnect','/admin/instagram/approve','/admin/instagram/edit','/admin/instagram/unschedule','/automation/drafts','/automation/opportunity-backup','/automation/status','/privacy','/data-deletion'].includes(path.split('?')[0]);},async handle(req,res){const url=new URL(req.url,origin);
  try{
   if(url.pathname==='/automation/status'){if(req.method!=='GET'||(typeof statusToken!=='string'||statusToken.length<32)||!equal(req.headers.authorization||'','Bearer '+statusToken))return send(res,401,'Unauthorized');const connection=vault.read(),posts=db.prepare('SELECT id,status,scheduled_at,published_id FROM instagram_queue ORDER BY scheduled_at,id').all();return send(res,200,JSON.stringify({meta:{configured:!!authorization,connected:!!connection,username:connection?.username||null},instagram:{counts:Object.fromEntries([...new Set(posts.map(x=>x.status))].map(status=>[status,posts.filter(x=>x.status===status).length])),posts}}),{'Content-Type':'application/json'});}
   if(req.method==='GET'&&url.pathname==='/privacy')return send(res,200,shell('<h1>Cancha automation privacy</h1><p>This service connects Cancha’s own Instagram account and stores content drafts, administrator review decisions and schedule times in private storage. Facebook and Instagram account identifiers and an encrypted Page publishing token are stored to enable approved publishing. User authorization tokens are processed during connection and are not kept as a personal login credential.</p><p>Organization, provider and offer submissions may include contact details. These are stored privately for Cancha review and are not added to the public website or Instagram automatically. Opportunity snapshots are encrypted in private storage. Hosting and Meta process the requests needed to provide this service.</p><p>Only authenticated administrators can use the review interface. The software provides no public contact-data or queue API. No automatic retention/deletion schedule is configured; administrators manage stored submissions and backups through private operational tools.</p><p><a href="/data-deletion">Disconnection and data-deletion instructions</a>. For requests about submitted information, contact Cancha through <a href="https://www.instagram.com/wearecancha/">@wearecancha</a>. Do not send passwords or access tokens.</p>'));
   if(req.method==='GET'&&url.pathname==='/data-deletion')return send(res,200,shell('<h1>Disconnect or request deletion</h1><p>Cancha account administrators can sign in to <a href="/admin">the private review interface</a> and choose Disconnect Instagram. This removes the stored publishing connection and cancels pending approved schedules. A request already being published may complete; check Instagram before retrying.</p><p>To revoke Meta’s grant, remove the Cancha app under Facebook Settings → Business integrations (or Apps and websites, depending on the app). Reconnection requires fresh authorization.</p><p>For submitted organization/provider/offer information, contact <a href="https://www.instagram.com/wearecancha/">@wearecancha</a> and identify the submission without sharing passwords or tokens. Cancha administrators must remove the applicable records and any retained copies through private operational access.</p>'));
   if(['/automation/drafts','/automation/opportunity-backup'].includes(url.pathname)){
    if(req.method!=='POST'||(typeof ingestSecret!=='string'||ingestSecret.length<32))return send(res,403,'Unavailable');if(!String(req.headers['content-type']).startsWith('application/json'))return send(res,415,'JSON required');const bytes=await body(req,url.pathname.endsWith('opportunity-backup')?4_000_000:65536),timestamp=String(req.headers['x-cancha-timestamp']||''),signature=String(req.headers['x-cancha-signature']||'');if(!/^\d{13}$/.test(timestamp)||Math.abs(Date.now()-Number(timestamp))>5*60000||!/^sha256=[a-f0-9]{64}$/.test(signature)||!equal(signature,ingestSignature(ingestSecret,timestamp,bytes)))return send(res,401,'Unauthorized');
    if(url.pathname.endsWith('opportunity-backup')){const snapshot=JSON.parse(bytes);if(snapshot.projectId!=='GU8EIeQXaRbty0S23thu'||snapshot.collectionName!=='Opportunities'||!Array.isArray(snapshot.items)||!Array.isArray(snapshot.fields)||!Number.isFinite(Date.parse(snapshot.capturedAt)))throw Error('Invalid snapshot');const hash=vault.saveBackup(snapshot);return send(res,201,JSON.stringify({stored:true,hash}),{'Content-Type':'application/json'});}
    const hash=createHash('sha256').update(bytes).digest('hex');if(db.prepare('SELECT hash FROM ingest_receipts WHERE hash=?').get(hash))return send(res,200,'Draft batch already received');const rows=JSON.parse(bytes);if(!Array.isArray(rows)||rows.length>5)throw Error('Invalid draft batch');
    db.exec('BEGIN');try{for(const source of rows){if(!/^opportunity-\d+$/.test(source.id||'')||source.sourceType!=='opportunity'||source.format!=='feed'||new URL(source.assetUrl).origin!=='https://framerusercontent.com'||!Number.isFinite(Date.parse(source.factsCheckedAt))||Date.parse(source.factsCheckedAt)>Date.now()||Date.now()-Date.parse(source.factsCheckedAt)>72*3600000||source.caption?.length>2200||new URL(source.assetUrl).username||new URL(source.assetUrl).password||!/^https:\/\/framerusercontent\.com\/images\/[^?]+\.jpe?g$/.test(source.assetUrl)||!/^[a-f0-9]{64}$/.test(source.assetChecksum||''))throw Error('Invalid source draft');const row=Object.fromEntries(['id','format','sourceType','factsCheckedAt','kicker','headline','body','cta','caption','altText','assetUrl','assetChecksum','rights','officialSourceUrl','sourceHash','sourcePostingId'].map(k=>[k,source[k]]));saveDraft(db,row);}db.prepare('INSERT INTO ingest_receipts VALUES(?,?)').run(hash,new Date().toISOString());db.exec('COMMIT');}catch(error){db.exec('ROLLBACK');throw error;}return send(res,201,'Drafts saved for review; nothing scheduled');
   }
   if(req.method==='POST'&&req.headers.origin!==origin)return send(res,403,'Origin rejected');
   if(url.pathname==='/admin/login'&&req.method==='POST'){
    const ip=req.socket.remoteAddress,record=attempts.get(ip)||{count:0,expires:Date.now()+10*60000};if(record.expires<Date.now()){record.count=0;record.expires=Date.now()+10*60000;}if(record.count>=10)return send(res,429,'Try again later');const values=new URLSearchParams((await body(req,4096)).toString());if(!equal(values.get('password')||'',password)){record.count++;attempts.set(ip,record);return send(res,401,shell('<h1>Sign-in failed</h1><a href="/admin">Try again</a>'));}attempts.delete(ip);return redirect(res,'/admin',{'Set-Cookie':`cancha_admin=${session()}; Path=/; Secure; HttpOnly; SameSite=Lax; Max-Age=3600`});
   }
   if(!authenticated(req)){if(req.method==='GET'&&url.pathname==='/admin')return send(res,200,shell('<h1>Cancha administrator sign-in</h1><form action="/admin/login" method="post"><label>Administrator password<input name="password" type="password" autocomplete="current-password" required></label><button>Sign in</button></form>'));return send(res,401,'Administrator sign-in required');}
   if(url.pathname==='/admin'&&req.method==='GET')return send(res,200,render());
   if(url.pathname==='/admin/logout'&&req.method==='POST')return redirect(res,'/admin',{'Set-Cookie':'cancha_admin=; Path=/; Secure; HttpOnly; SameSite=Lax; Max-Age=0'});
   if(url.pathname==='/admin/meta/disconnect'&&req.method==='POST'){vault.clear();db.prepare("UPDATE instagram_queue SET status='Draft',approved_hash=NULL,approved_by=NULL,scheduled_at=NULL,container_id=NULL,note='Instagram disconnected; review and reconnect before scheduling' WHERE status IN ('Approved','Preparing')").run();return redirect(res,'/admin');}
   if(url.pathname==='/auth/meta/start'&&req.method==='POST'){if(!authorization)return send(res,503,'Complete the Meta app configuration first');const state=vault.createState();return redirect(res,authorization.url(state),{'Set-Cookie':`cancha_meta_state=${state}; Path=/auth/meta/callback; Secure; HttpOnly; SameSite=Lax; Max-Age=600`});}
   if(url.pathname==='/auth/meta/callback'&&req.method==='GET'){
    const state=url.searchParams.get('state')||'';if(!authorization||url.searchParams.has('error')||!equal(cookie(req,'cancha_meta_state'),state)||!vault.consumeState(state))return send(res,400,'Connection canceled or state expired. Sign in and reconnect.');const connection=await authorization.exchange(url.searchParams.get('code'));vault.save(connection);return redirect(res,'/admin',{'Set-Cookie':'cancha_meta_state=; Path=/auth/meta/callback; Secure; HttpOnly; SameSite=Lax; Max-Age=0'});
   }
   if(url.pathname==='/admin/instagram/approve'&&req.method==='POST'){
    const connection=vault.read();if(!connection)return send(res,409,'Connect Instagram first');const values=new URLSearchParams((await body(req,4096)).toString());if(values.get('reviewed')!=='yes')return send(res,422,'Review confirmation required');const item=db.prepare('SELECT content FROM instagram_queue WHERE id=?').get(values.get('id'));if(!item)return send(res,404,'Draft not found');if(JSON.parse(item.content).format==='story'&&connection.accountType!=='BUSINESS')return send(res,422,'API Stories require a confirmed Business account; verify the account type in settings and reconnect.');const content=JSON.parse(item.content);if(content.sourceType==='opportunity'){await confirmOpportunitySource(content,{fetchImpl});db.prepare('UPDATE instagram_queue SET source_rechecked_at=? WHERE id=?').run(new Date().toISOString(),values.get('id'));}approve(db,values.get('id'),{reviewer,scheduledAt:newYorkSchedule(values.get('scheduledAt')),allowSourceRecheck:content.sourceType==='opportunity'});return redirect(res,'/admin');
   }
   if(url.pathname==='/admin/instagram/edit'&&req.method==='POST'){const values=new URLSearchParams((await body(req,10000)).toString()),item=db.prepare('SELECT * FROM instagram_queue WHERE id=?').get(values.get('id'));if(!item||item.status!=='Draft')return send(res,409,'Unschedule before editing');const caption=values.get('caption')?.trim(),altText=values.get('altText')?.trim();if(!caption||caption.length>2200||!altText||altText.length>1000)return send(res,422,'Caption and alt text are required and must fit Instagram limits');saveDraft(db,{...JSON.parse(item.content),caption,altText});return redirect(res,'/admin');}
   if(url.pathname==='/admin/instagram/unschedule'&&req.method==='POST'){const values=new URLSearchParams((await body(req,4096)).toString());const changed=db.prepare("UPDATE instagram_queue SET status='Draft',approved_hash=NULL,approved_by=NULL,scheduled_at=NULL,container_id=NULL,note='Schedule canceled by the administrator; review again before scheduling' WHERE id=? AND status IN ('Approved','Preparing')").run(values.get('id'));if(!changed.changes)return send(res,409,'This post is no longer cancelable here; check publishing status');return redirect(res,'/admin');}
   return send(res,404,'Not found');
  }catch(error){if(url.pathname==='/auth/meta/callback'){const known=error instanceof MetaConnectionError;const code=known?error.code:'META_CALLBACK_FAILED';const detail=known?error.message:'The connection could not be saved. Start a new connection from the dashboard. If it fails again, check private storage and Meta app settings in Render.';const numbers=known&&error.metaCode!==null?' — Meta code '+error.metaCode+(error.metaSubcode!==null?', subcode '+error.metaSubcode:''):'';return send(res,422,shell('<h1>Instagram connection needs attention</h1><p><strong>'+esc(code+numbers)+'</strong></p><p>'+esc(detail)+'</p><p>Do not refresh this callback page or share its address. Return to the dashboard and start a new connection after correcting the settings.</p><a href="/admin">Return to review</a>'));}return send(res,422,shell('<h1>Action needs attention</h1><p>Check the content, future schedule, fresh source facts or Meta app configuration. No automatic retry of publishing is performed.</p><a href="/admin">Return to review</a>'));}
 },close(){db.close();vault.close();},vault,db};
}
