import {requiresSource} from './post-source.mjs';
import {createHash} from 'node:crypto';
import {DatabaseSync} from 'node:sqlite';
import {mkdirSync,chmodSync} from 'node:fs';import {dirname} from 'node:path';
export const contentHash=row=>createHash('sha256').update(JSON.stringify({id:row.id,format:row.format,caption:row.caption,altText:row.altText,assetUrl:row.assetUrl,sourceType:row.sourceType,factsCheckedAt:row.factsCheckedAt,headline:row.headline,body:row.body,kicker:row.kicker,cta:row.cta,assetChecksum:row.assetChecksum,sourceHash:row.sourceHash,officialSourceUrl:row.officialSourceUrl})).digest('hex');
export function openQueue(path){mkdirSync(dirname(path),{recursive:true,mode:0o700});const db=new DatabaseSync(path);chmodSync(path,0o600);db.exec(`CREATE TABLE IF NOT EXISTS instagram_queue(id TEXT PRIMARY KEY,content TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'Draft',approved_hash TEXT,approved_by TEXT,scheduled_at TEXT,container_id TEXT,published_id TEXT,note TEXT NOT NULL DEFAULT '')`);if(!db.prepare('PRAGMA table_info(instagram_queue)').all().some(x=>x.name==='source_rechecked_at'))db.exec('ALTER TABLE instagram_queue ADD COLUMN source_rechecked_at TEXT');return db;}
export function saveDraft(db,row){if(!row.id||!['feed','story'].includes(row.format)||!row.caption||!row.altText)throw Error('Invalid content');const existing=db.prepare('SELECT * FROM instagram_queue WHERE id=?').get(row.id);if(existing&&existing.content===JSON.stringify(row))return;if(existing&&['Publishing','Published','Needs reconciliation'].includes(existing.status))throw Error('Cannot overwrite a dispatched row');db.prepare("INSERT INTO instagram_queue(id,content) VALUES(?,?) ON CONFLICT(id) DO UPDATE SET content=excluded.content,status='Draft',approved_hash=NULL,approved_by=NULL,scheduled_at=NULL,container_id=NULL,note=''").run(row.id,JSON.stringify(row));}
export function approve(db,id,{reviewer,scheduledAt,now=Date.now(),allowSourceRecheck=false}){const stored=db.prepare('SELECT * FROM instagram_queue WHERE id=?').get(id);if(!stored||stored.status!=='Draft')throw Error('A draft is required');const row=JSON.parse(stored.content);if(!reviewer?.trim()||!/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(?:\.\d{3})?Z$/.test(scheduledAt)||Date.parse(scheduledAt)<=now)throw Error('Reviewer and a future UTC timestamp are required');const url=new URL(row.assetUrl);if(url.protocol!=='https:'||url.username||url.password)throw Error('An approved public HTTPS JPEG asset is required');if(!row.assetUrl.toLowerCase().split('?')[0].endsWith('.jpg')&&!row.assetUrl.toLowerCase().split('?')[0].endsWith('.jpeg'))throw Error('Use an actual public JPEG asset URL');if(requiresSource(row)&&(!Number.isFinite(Date.parse(row.factsCheckedAt))||Date.parse(row.factsCheckedAt)>now||(!allowSourceRecheck&&Date.parse(scheduledAt)-Date.parse(row.factsCheckedAt)>72*3600000)))throw Error('Recheck opportunity facts within 72 hours of publication');db.prepare("UPDATE instagram_queue SET status='Approved',approved_hash=?,approved_by=?,scheduled_at=? WHERE id=?").run(contentHash(row),reviewer.trim(),new Date(scheduledAt).toISOString(),id);}
export async function dispatchDue(db,publisher,{now=Date.now(),limit=5,verifySource}={}){
 const due=db.prepare("SELECT * FROM instagram_queue WHERE status IN ('Approved','Preparing') AND scheduled_at<=? ORDER BY scheduled_at LIMIT ?").all(new Date(now).toISOString(),limit),results=[];
 for(const stored of due){const row=JSON.parse(stored.content);let sourceFresh=false;if(requiresSource(row)&&verifySource){try{if(await verifySource(row)!==true)throw Error('Source confirmation failed');sourceFresh=true;db.prepare('UPDATE instagram_queue SET source_rechecked_at=? WHERE id=?').run(new Date(now).toISOString(),row.id);}catch{db.prepare("UPDATE instagram_queue SET status='Draft',note='Organizer source changed, closed or unavailable; review again before scheduling' WHERE id=?").run(row.id);continue;}}if(contentHash(row)!==stored.approved_hash){db.prepare("UPDATE instagram_queue SET status='Draft',note='Content changed after approval' WHERE id=?").run(row.id);continue;}if(requiresSource(row)&&!sourceFresh&&(!Number.isFinite(Date.parse(row.factsCheckedAt))||Date.parse(row.factsCheckedAt)>now||now-Date.parse(row.factsCheckedAt)>72*3600000)){db.prepare("UPDATE instagram_queue SET status='Draft',note='Official facts need rechecking' WHERE id=?").run(row.id);continue;}
  // A source check yields to edits, cancellations and plan pauses. Re-read
  // approval before creating any Meta container; do not resurrect a canceled row.
  const current=db.prepare('SELECT * FROM instagram_queue WHERE id=?').get(row.id);
  if(!current||!['Approved','Preparing'].includes(current.status)||current.approved_hash!==stored.approved_hash||current.scheduled_at!==stored.scheduled_at||contentHash(JSON.parse(current.content))!==contentHash(row))continue;
  let container=stored.container_id;
  if(!container){db.prepare("UPDATE instagram_queue SET status='Preparing' WHERE id=?").run(row.id);try{container=await publisher.create(row);const saved=db.prepare("UPDATE instagram_queue SET container_id=? WHERE id=? AND status='Preparing' AND approved_hash=?").run(container,row.id,stored.approved_hash);if(saved.changes!==1)continue;}catch{db.prepare("UPDATE instagram_queue SET status='Failed',note='Container creation failed; check account and asset before manual retry' WHERE id=?").run(row.id);results.push({id:row.id,status:'Failed'});continue;}}
  let state;try{state=await publisher.status(container);}catch{results.push({id:row.id,status:'Preparing'});continue;}
  if(state==='IN_PROGRESS'){results.push({id:row.id,status:'Preparing'});continue;}
  if(state!=='FINISHED'){db.prepare("UPDATE instagram_queue SET status='Failed',note='Container is not publishable; manual review required' WHERE id=?").run(row.id);results.push({id:row.id,status:'Failed'});continue;}
  // Claim before the irreversible call. Never automatically repeat an ambiguous publish.
  const claimed=db.prepare("UPDATE instagram_queue SET status='Publishing' WHERE id=? AND status IN ('Approved','Preparing')").run(row.id);if(claimed.changes!==1)continue;
  try{const published=await publisher.publish(container);db.prepare("UPDATE instagram_queue SET status='Published',published_id=? WHERE id=?").run(published,row.id);results.push({id:row.id,status:'Published'});}catch{db.prepare("UPDATE instagram_queue SET status='Needs reconciliation',note='Publishing outcome uncertain; check Instagram before any retry' WHERE id=?").run(row.id);results.push({id:row.id,status:'Needs reconciliation'});}
 }
 return results;
}
export function metaPublisher({token,accountId,version,accountType,fetchImpl=fetch}){
 if(!token||!/^\d+$/.test(accountId)||!/^v\d+\.\d+$/.test(version))throw Error('Secure Meta token, account ID and supported Graph version required');
 const base=`https://graph.facebook.com/${version}`;
 async function call(path,params,method='POST'){const url=new URL(base+'/'+path);if(method==='GET')for(const[k,v]of Object.entries(params))url.searchParams.set(k,v);const actualToken=typeof token==='function'?await token():token;if(!actualToken)throw Error('Meta reconnection required');const response=await fetchImpl(url,{method,headers:{Authorization:'Bearer '+actualToken,...(method==='POST'?{'Content-Type':'application/x-www-form-urlencoded'}:{})},body:method==='POST'?new URLSearchParams(params):undefined,signal:AbortSignal.timeout(30000)});if(!response.ok)throw Error('Meta request failed');return response.json();}
 return {create:async row=>{if(row.format==='story'&&accountType!=='BUSINESS')throw Error('Story publishing requires a confirmed Business account');const result=await call(accountId+'/media',{image_url:row.assetUrl,...(row.format==='story'?{media_type:'STORIES'}:{caption:row.caption,alt_text:row.altText})});if(!result.id)throw Error('Missing container ID');return result.id;},status:async id=>(await call(id,{fields:'status_code'},'GET')).status_code,publish:async id=>{const result=await call(accountId+'/media_publish',{creation_id:id});if(!result.id)throw Error('Missing publication ID');return result.id;}};
}
