import {readFile} from 'node:fs/promises';import {flattenSchemas,sourceDigest} from './source-verification.mjs';
const text=s=>String(s).replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,'').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim();
export function jobEvidence(html,url){const schemas=[];const scripts=/<script\b[^>]*type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;for(const match of html.matchAll(scripts)){try{schemas.push(JSON.parse(match[1]));}catch{}}
 const applicationLinks=[];for(const match of html.matchAll(/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi))if(/apply now/i.test(text(match[2])))applicationLinks.push(new URL(match[1].replaceAll('&amp;','&'),url).href);
 const jobs=flattenSchemas(schemas).filter(x=>[x['@type']].flat().includes('JobPosting')),links=[...new Set(applicationLinks)].sort(),closed=/closed to new applications|position (?:has been )?filled|no longer accepting applications/i.test(text(html));return {jobs,applicationLinks:links,closed,hash:sourceDigest(Buffer.from(JSON.stringify({jobs,applicationLinks:links,closed})))};
}
export async function confirmOpportunitySource(row,{fetchImpl=fetch,registry}={}){registry||=JSON.parse(await readFile('config/automated-organizers.json','utf8'));if(!registry.some(x=>row.officialSourceUrl?.startsWith(x.sourcePrefix))||!/^[a-f0-9]{64}$/.test(row.sourceHash||''))throw Error('No supported source proof; regenerate this draft');const response=await fetchImpl(row.officialSourceUrl,{redirect:'manual',signal:AbortSignal.timeout(20000)});if(response.status!==200||!/text\/html/i.test(response.headers.get('content-type')||'')){await response.body?.cancel();throw Error('Organizer source is unavailable; keep the post in review');}const reader=response.body.getReader(),chunks=[];let length=0;while(true){const result=await reader.read();if(result.done)break;length+=result.value.length;if(length>2_000_000){await reader.cancel();throw Error('Source exceeds review size limit');}chunks.push(Buffer.from(result.value));}
 const evidence=jobEvidence(Buffer.concat(chunks).toString('utf8'),row.officialSourceUrl);if(evidence.closed||evidence.jobs.length!==1||evidence.hash!==row.sourceHash)throw Error('Organizer source changed or closed; regenerate and review the draft');const job=evidence.jobs[0];if(job.validThrough&&(!Number.isFinite(Date.parse(job.validThrough))||Date.parse(job.validThrough)<=Date.now()))throw Error('Organizer metadata is stale; review before publishing');return true;
}
